### PR TITLE
Better selection interface

### PR DESCRIPTION
**Pull request by karthink**
Hi @corytertel,

I noticed you added more functions from meow in #8d6496d3.  Incidentally, I've been writing something similar over the last couple of days.  Meow's interface for secondary selection is tedious and annoying, I think we can do *much* better, with a single command.  Here's what I'm thinking:

## Select from region and cycle

This command, temporarily named `macrursors-sel-cycle`, works as follows.

- If a region is active, convert it to a secondary selection (same as meow's `swap-grab`).
- If you select a region while the secondary selection is active and call `macrursors-sel-cycle`, it moves the selection to the region (same as `macrursors-sync-grab`.)
- The command can be called repeatedly by just pressing `SPC`.
- Calling it again will cycle the selection between a few syntactic units.  In prog-mode that's `defun`, `expression` or `list` and `line`:

_(See top right for the keys I'm pressing)_

https://user-images.githubusercontent.com/8607532/217716433-69f6befb-e95e-41f6-8a49-18463fe01cf1.mp4

In text-mode it's `page`, `paragraph`, `sentence` and `line`, and so on. (See below for caveats)

- If region isn't active, it starts off by selecting from the top of the list, i.e. `defun` here.

## Update selection

Of course, it's rare when editing to mark the scope first and then start macrursors.  Usually we do it the other way -- mark all instances of something and then limit the scope.  `macrursors-sel-cycle` will update the cursors when called.

### Syntactic marks (lines, words etc)

https://user-images.githubusercontent.com/8607532/217718325-e7eb23a5-adad-441a-bd9e-6ec339c712ca.mp4

https://user-images.githubusercontent.com/8607532/217718548-78420178-2200-4715-9545-4873b6fea248.mp4

### Regions or strings

https://user-images.githubusercontent.com/8607532/217718716-d778b1ea-43ea-4a3f-9672-eb7ca4203c1c.mp4

This way you can easily modify how you want to limit edits.

## Working with other packages

There are many packages that provide region selection features, like `expand-region`, `easy-mark`, various text-object packages for `evil-mode`, and we'll soon have many more thanks to tree-sitter.  So we don't want to duplicate this work in `macrursors`, and instead provide only the most common and basic textual units.  I'm trying to write an interface that will allow `macrursors-sel-cycle` to work with them.  In the worst case, you can always select the region first using one of these packages and then convert it to a secondary selection.  Here's an example of using it with `expand-region`:

https://user-images.githubusercontent.com/8607532/217719455-76e9dc91-c7e2-4055-b633-9ccfa90b5925.mp4

(Note that support for `expand-region` is _not_ intended to be part of `macrursors`.)

## Structuring `macrursors-select`

This is currently not much code at all, it's around 110 lines.  I like the idea of keeping `macrursors.el` focused and very simple, so I'm writing this in a separate file (`macrursors-select.el`).  It will generate a single `autoload` for `macrursors-sel-cycle`, and the file won't be loaded along with macrursors.

I've been using the selection cycling/updates continuously and it's pretty good.  Let me know if you're interested in a PR for this feature, in which case we can get rid of the secondary selection code adapted from meow.

### CODE REVIEW

**Comment by corytertel** [comment]
The idea for `macrursors-sel-cycle` is very interesting and I love it. It seems to be much more intuitive than the existing selection method. I especially love the idea to change the region the cursors are in even after they are marked. 

While the idea for macrursors is to be as minimal as possible, I'm not opposed to adding ways to extend macrursors to work with selection packages. 

If this is opened as a PR I'll approve it as it seems that this could be a drastic increase in usability.

**Comment by karthink** [comment]
Thank you for the encouragement @corytertel. Will clean up the code and submit a PR today.

**Comment by karthink** [comment]
Okay, here's the rundown of the feature:

1. There is one selection command: `macrursors-select`.  It turns the region into a secondary selection (if the region is active), or else cycles through some basic major-mode specific text units.  If `macrursors-mode` is active, cursors are updated as the selection changes.

2. The selection functionality is isolated to `macrursors-select.el`.  Folks who don't use secondary selections will never have to load this file.  `macrursors.el` also stays clean and small.

3. There is a new variable `macrursors--instance`.  This holds the "thing" we searched for when creating cursors.  This is required for updating cursors, but can have other uses in the future too.

4. There is one other command, `macrursors-mark-from-isearch`: This creates cursors at positions of the current isearch candidate, as in issue #2.  This code _is_ part of `macrursors.el`.  (It's a single defun and it seemed to fit in with the other mark-all commands in that file.)

5. No keys are bound in the global or isearch map for the interactive commands introduced by this PR.  However, `macrursors-select` is bound to `SPC` in the transient keymap that allows for one-key selection cycling.  Similarly, the secondary selection can be cleared with `C-g` (when cycling) or with `C-g` in `macrursors-mark-map` (at any time).

6. The secondary selection code adapted from Meow has been removed as it is completely redundant compared to `macrursors-select`.

7. Writing a generic adapter that can work with every selection package is tough because of how different their interfaces are.  I'll think more on this, but for now I'm content to support expand-region.  This isn't part of the PR, and you can let me know if support for expand-region and a few more common selection packages should be part of a separate file, let's say `macrursors-extra.el` or `macrursors-select-integrations.el`.

------

Do you think we should automatically clear the secondary selection after exiting `macrursors-mode`?  The current way to clear it is covered in point 5 above.  Auto-clearing the secondary selection might frustrate users who have marked a region or defun and are doing a series of refactorings inside it, for instance.

**Comment by corytertel** [comment]
> If `macrursors-mode` is active, cursors are updated as the selection changes.

Possibly the best feature so far.

> The selection functionality is isolated to `macrursors-select.el`. Folks who don't use secondary selections will never have to load this file. `macrursors.el` also stays clean and small.

This is quite a good idea; it keeps the package small. There's another benefit to macrursors' selection being isolated. Because we don't force users to use macrursors' selection for the package to work, this leaves the door open for users to implement their own selection. If a user wants to use a selection package of their choice, they can do so, which indirectly provides a "solution" for point #7.

> No keys are bound in the global or isearch map for the interactive commands introduced by this PR. However, macrursors-select is bound to SPC in the transient keymap that allows for one-key selection cycling. Similarly, the secondary selection can be cleared with C-g (when cycling) or with C-g in macrursors-mark-map (at any time).

In the fufure we may need to find a better way to cancel, or maybe a way to determine whether or not to clear the cursors after applying edits. I think we could to this in a custom variable, where the user could set to clear or not to clear the cursors after applying edits.

**Pull request merged**
